config/routes.rb
Vishnuapp::Application.routes.draw do

=begin
  get "colleges/:index"

  get "colleges/:show"

  get "colleges/:new"

  get "colleges/:edit"

  get "colleges/:update"

  get "colleges/:create"
=end
  resources :students do  # ,    only: [ :index ] 
    member do    
    end

    collection do
      get "doquery"  
      get "queries"
    end
  end  

  resources :colleges do
      member do 
      end

      collection do
      
        get "results"
        get "listing"
      end
  end  

end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :IDno, :chemistry, :department, :maths, :physics, :year, :college_id, :extendedId
    belongs_to :college

    before_create :func_extendedsid1

    before_update :func_extendedsid

    def func_extendedsid
    	 
    	student_id = self.IDno.to_s
    	college_twoletters = College.find(self.college_id)[:college_name][0,2]
    	collegeId = self.college_id.to_s
    	self.extendedId = student_id << "_" << college_twoletters << "_" << collegeId
    	
    end

    def func_extendedsid1
    	 
    	student_id = self.IDno.to_s
    	college_twoletters = College.find(self.college_id)[:college_name][0,2]
    	collegeId = self.college_id.to_s
    	self.extendedId = student_id << "_" << college_twoletters << "_" << collegeId
    	
    end
end


#Rails.logger.debug "Updatinppp2222222222gggggggggggggg Record #{student_id.inspect}"

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  
	def index
	  	@students = Student.all
	end

	def show	  
		@student = Student.find(params[:id])
		respond_to do |format|
			format.json do
			    render json: @student.to_json
			end

			format.html do
			end
		end
	end

	def new
	  	@students = Student.new
	end

	def edit
	  	@students = Student.find(params[:id])
	end

	def update
	  	@student = Student.find(params[:id])
	  	@student.update_attributes(params["students"])
	  	redirect_to action: :index
	end

	def destroy
	  	@student = Student.find(params[:id])
	  	@student.destroy
	  	redirect_to action: :index
	end

	def create
	  	@students = Student.create(params[:students])
	  	redirect_to action: :new
	end

	def find_by
		
	end

	def doquery
	  	
	end

	def queries
	  	data = Student.all
	  	datatable_cpy= Array.new
	  	data_db= Array.new
	  	datatable_another_cpy = Array.new

	  	for i in 0..(data.length-1)
	  		datatable_cpy[i] = {:IDno=>data[i].IDno, :department=>data[i].department, :maths=>data[i].maths, :physics=>data[i].physics, :chemistry=>data[i].chemistry, :year=>data[i].year }
	  	end

	  	for i in 0..(data.length-1)
	  		data_db[i]= {:IDno=>data[i].IDno, :department=>data[i].department, :maths=>data[i].maths, :physics=>data[i].physics, :chemistry=>data[i].chemistry, :year=>data[i].year }
	  	end

	    for i in 0..(data.length-1)
	  		datatable_another_cpy[i] = { :IDno=>data[i].IDno, :department=>data[i].department, :maths=>data[i].maths, :physics=>data[i].physics, :chemistry=>data[i].chemistry, :year=>data[i].year }
	  	end
	  	
	  	grouping(params[:groupby],datatable_cpy,datatable_another_cpy)
	  	sorting(params[:sortby],params[:groupby])
	  	@grpby_id_dept_year = params[:groupby]
	  	compare(params[:compareby])
	  	total_show(data_db)
	end

    def group_keys(array)
		keyy = array[0].keys
		keyy.delete(:maths)
		keyy.delete(:physics)
		keyy.delete(:chemistry)
		return keyy
	end
		
 	def grouping(groupby,array_arg,array)
		keyy = group_keys(array)
		@mean_hash=Hash.new
		grouped_array = Hash.new
		
		keyy.each do |n| 
			if n.to_s == groupby.to_s
				grouped_array = array_arg.group_by{|h| h[n.to_sym]}
				grouped_array.each_key do |k|
					for i in 0..(grouped_array[k].length-1)
				 		grouped_array[k][i].delete(:IDno)
				 		grouped_array[k][i].delete(:department)
				 		grouped_array[k][i].delete(:year)
				 	end 	
				end

				grouped_array.each_key do |k|
					average_values = grouped_array[k].map(&:values).transpose.map { |arr| 
					arr.map(&:to_f).inject(:+) / arr.size 
																		 }
					with_keys = Hash[grouped_array[k].first.keys.zip(average_values)]
					@mean_hash[k]=with_keys
				end
			end			
		end
	end
	
	def sorting(sortby,groupby)
		meanhash_to_arr_of_hashes = Array.new
		mean_arr = Array.new
		mean_arr_values = Array.new
		mean_arr_keys = Array.new
		temp = Hash.new
		@sorted = []
		mean_arr_values = @mean_hash.values
		mean_arr_keys   = @mean_hash.keys

		for i in 0..(mean_arr_keys.length-1)
			temp[groupby.to_sym] = mean_arr_keys[i]
			mean_arr_values[i] = temp.merge(mean_arr_values[i])
			meanhash_to_arr_of_hashes[i] = mean_arr_values[i]
		end
		mean_arr = @mean_hash.values[0].keys
		mean_arr.each do |p|
			if p.to_s == sortby.to_s
				@sorted = meanhash_to_arr_of_hashes.sort_by{|p| p[sortby.to_sym]}
			end
		end
	end

    def compare(id_dept)
		data = Student.all
		arr_cpy = Array.new
		for i in 0..(data.length-1)
	  		arr_cpy[i]= {:IDno=>data[i].IDno, :department=>data[i].department, :maths=>data[i].maths, :physics=>data[i].physics, :chemistry=>data[i].chemistry, :year=>data[i].year }
	  	end

	  	past_year=2015
			current_year=2016

		if id_dept == "IDno"
			new_array=arr_cpy.group_by{|h| h[:year]}
			year_length=new_array.length
			past_data=new_array[past_year.to_i].group_by{|h| h[:IDno]}
			current_data=new_array[current_year.to_i].group_by{|h| h[:IDno]}
            current_print=Hash.new
			past_print=Hash.new
			if(current_data.length>past_data.length)
				current_data.each_key do |k|
					if(!current_data.key?(k))
						temp=[{:year1=>current_year,:maths1=>0,:physics1=>0,:chemistry1=>0},{:year1=>past_year,:maths1=>past_data[k][0][:maths],:physics1=>past_data[k][0][:physics],:chemistry1=>past_data[k][0][:chemistry]},{:change=>"change",:maths1=>"infinity",:physics1=>"infinity",:chemistry1=>"infinity"}]
			        	current_print[k]=temp
			        elsif(!past_data.key?(k))
						temp=[{:year1=>current_year,:maths1=>current_data[k][0][:maths],:physics1=>current_data[k][0][:physics],:chemistry1=>current_data[k][0][:chemistry]},{:year1=>past_year,:maths1=>0,:physics1=>0,:chemistry1=>0},{:change=>"change",:maths1=>100,:physics1=>100,:chemistry1=>100}]
			        	current_print[k]=temp
			        else
						temp=[{:year1=>current_year,:maths1=>current_data[k][0][:maths],:physics1=>current_data[k][0][:physics],:chemistry1=>current_data[k][0][:chemistry]},{:year1=>past_year,:maths1=>past_data[k][0][:maths],:physics1=>past_data[k][0][:physics],:chemistry1=>past_data[k][0][:chemistry]},{:change=>"change",:maths1=>((current_data[k][0][:maths]-past_data[k][0][:maths]).to_f*100/current_data[k][0][:maths].to_f).round(2),:physics1=>((current_data[k][0][:physics]-past_data[k][0][:physics]).to_f*100/current_data[k][0][:physics].to_f).round(2),:chemistry1=>((current_data[k][0][:chemistry]-past_data[k][0][:chemistry]).to_f*100/current_data[k][0][:chemistry].to_f).round(2)}]
						current_print[k]=temp
					end
			    end
				@output_compared = current_print
			else
				past_data.each_key do |k|
					if(!current_data.key?(k))
						temp=[{:year1=>current_year,:maths1=>0,:physics1=>0,:chemistry1=>0},{:year1=>past_year,:maths1=>past_data[k][0][:maths],:physics1=>past_data[k][0][:physics],:chemistry1=>past_data[k][0][:chemistry]},{:change=>"change",:maths1=>"infinity",:physics1=>"infinity",:chemistry1=>"infinity"}]
			        	current_print[k]=temp
			        elsif(!past_data.key?(k))
						temp=[{:year1=>current_year,:maths1=>current_data[k][0][:maths],:physics1=>current_data[k][0][:physics],:chemistry1=>current_data[k][0][:chemistry]},{:year1=>past_year,:maths1=>0,:physics1=>0,:chemistry1=>0},{:change=>"change",:maths1=>100,:physics1=>100,:chemistry1=>100}]
			        	current_print[k]=temp
			        else
						temp=[{:year1=>current_year,:maths1=>current_data[k][0][:maths],:physics1=>current_data[k][0][:physics],:chemistry1=>current_data[k][0][:chemistry]},{:year1=>past_year,:maths1=>past_data[k][0][:maths],:physics1=>past_data[k][0][:physics],:chemistry1=>past_data[k][0][:chemistry]},{:change=>"change",:maths1=>((current_data[k][0][:maths]-past_data[k][0][:maths]).to_f*100/current_data[k][0][:maths].to_f).round(2),:physics1=>((current_data[k][0][:physics]-past_data[k][0][:physics]).to_f*100/current_data[k][0][:physics].to_f).round(2),:chemistry1=>((current_data[k][0][:chemistry]-past_data[k][0][:chemistry]).to_f*100/current_data[k][0][:chemistry].to_f).round(2)}]
						current_print[k]=temp
					end
			    end
				@output_compared = current_print
			end
		elsif id_dept == "department"
			grpby_year = arr_cpy.group_by{|h| h[:year]} 
			@final = Hash.new
			current_data = grpby_year[current_year].group_by{|h| h[:department]}
			past_data = grpby_year[past_year].group_by{|h| h[:department]}
			current_data.each_key do |k|
				c_data_len = current_data[k].size
				math_sum = 0;phy_sum = 0; chem_sum = 0;
				for i in 0..(c_data_len-1)
					math_sum = math_sum + current_data[k][i][:maths].to_f
					phy_sum = phy_sum + current_data[k][i][:physics].to_f
					chem_sum = chem_sum + current_data[k][i][:chemistry].to_f
				end
				@avg_current_year[k] = {:maths=> (math_sum/c_data_len).round(2), :physics=> (phy_sum/c_data_len).round(2), :chemistry=>(chem_sum/c_data_len).round(2), :year=>current_year }
				p_data_len = past_data[k].size
				math_sum = 0;phy_sum = 0; chem_sum = 0;
				for i in 0..(p_data_len-1)
					math_sum = math_sum + past_data[k][i][:maths].to_f
					phy_sum = phy_sum + past_data[k][i][:physics].to_f
					chem_sum = chem_sum + past_data[k][i][:chemistry].to_f
				end
				@avg_past_year[k] = {:maths=> (math_sum/p_data_len).round(2), :physics=> (phy_sum/p_data_len).round(2), :chemistry=>(chem_sum/p_data_len).round(2), :year=>past_year }
								
			end
			@avg_past_year.each_key {|k|
				math_avg_dept = percent_change(@avg_current_year[k][:maths],@avg_past_year[k][:maths])
				phys_avg_dept = percent_change(@avg_current_year[k][:physics],@avg_past_year[k][:physics])
				chem_avg_dept = percent_change(@avg_current_year[k][:chemistry],@avg_past_year[k][:chemistry])
				@current_print[k] = {:maths=> math_avg_dept, :physics=>  phys_avg_dept, :chemistry=> chem_avg_dept, :change=>"change"}
			}
			@output_compared = @current_print
		else
			@output_compared = "No comparison"
		end
	end

	def percent_change(first_entry,second_entry) 
		if second_entry == 0
    		return 100
    	elsif first_entry == 0
    		return "infinity"
    	else 
    		return ((first_entry - second_entry).to_f * 100/first_entry.to_f).round(2)	
    	end
    end

    def total_show(data)
		@sum_hash = Array.new
		data_grouped_sum = Hash.new
		data_grouped_sum_values=Array.new
		mean_arr_values = Array.new
		data_grouped_sum_keys = Array.new
		sumhash_to_arr_of_hashes=Array.new
		for i in 0..(data.length-1)
			data[i].delete(:IDno)
			data[i].delete(:department)
		end
		data = data.group_by{|k| k[:year]}
		data.each_key do |s|
			average_values = data[s].map(&:values).transpose.map { |arr| 
			arr.map(&:to_f).inject(:+) / 1 
																 }
			with_keys = Hash[data[s].first.keys.zip(average_values)]
			data_grouped_sum[s] = with_keys
		end
		data_grouped_sum.each_key do |h|
			data_grouped_sum[h].delete(:year)
		end
		data_grouped_sum_values = data_grouped_sum.values
		data_grouped_sum_keys   = data_grouped_sum.keys
		for i in 0..(data_grouped_sum_keys.length-1)
			temp = Hash.new
			temp[:year] = data_grouped_sum_keys[i]
			data_grouped_sum_values[i] = temp.merge(data_grouped_sum_values[i])
		end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/doquery.html.erb
<div>
	<%= form_for :students,url: {action: "queries", controller: "students"},method: "get"  do |f| %> 
	<p>

	  Groupby:
		
		<select name = "groupby">
			<option value ="IDno"> IDno</option>
			<option value = "department" >department</option>
			<option value = "year" >year</option>
			<option value = "none" >none</option>
		</select>

	</p>

	<p>
	  Sortby:
		<select name = "sortby">
			<option value ="maths"> maths</option>
			<option value = "physics" >physics</option>
			<option value = "chemistry" >chemistry</option>
			<option value = "none" >none</option>
		</select>
	</p>

	<p>
	    Display by maths/physics/chemitry:<%= check_box_tag "active", 1, true%>
	</p>


	<p>
		Do you want comparison:
		<select name = "compareby">
			<option value ="IDno"> IDno</option>
			<option value = "department" >department</option>
			<option value = "none" >none</option>
		</select>
	</p>

	<p>
	 	show total:<%= check_box_tag "active2", 1, true %>
	</p>

	<p>

	</p>
		<input type="submit" value="Submit">
	<% end %>
</div>

app/views/students/edit.html.erb
<div>
  <%= form_for :students,url: { action: "update",controller: "students"}, method:"put" do |f|%>

        <%= f.label :IDno %>
        <%= f.text_field :IDno %><br />

        <%= f.label :college_id %>
        <%= f.text_field :college_id %><br />

        <%= f.label :department %>
        <%= f.text_field :department %><br />

        <%= f.label :maths %>
        <%= f.text_field :maths %><br />

        <%= f.label :physics %>
        <%= f.text_field :physics %><br />

        <%= f.label :chemistry %>
        <%= f.text_field :chemistry %><br />

        <%= f.label :year%>
        <%= f.text_field :year %><br />

        <%= f.submit %>
    <%end %>
</div>

app/views/students/index.html.erb
<div>
	<style>
    	table, tr, td {
        border: 1px solid black;
        border-collapse: collapse;
	    }
	</style>
		<table style="width:70%" border = "0">
		  <tr>
		  	<td>id</td>
		  	<td>college_id</td>
		  	<td>extendedId</td>
		    <td>IDno</td>
		    <td>department</td>
		    <td>maths</td>
		    <td>physics</td>
		    <td>chemistry</td>
		    <td>year</td>
		    <td>actions</td>
		  </tr>
		 <% @students.each do |students| %>
			<tr>
				<td><%= students.id %> </td> 
				<td><%= students.college_id %> </td> 
				<td><%= students.extendedId %> </td>
				<td><%= students.IDno %> </td> 
				<td><%= students.department %></td>
			    <td><%= students.maths %></td>
			    <td><%= students.physics %></td>
			    <td><%= students.chemistry %></td>
			    <td><%= students.year %></td>
			    <td><%= link_to "show" ,student_path(students),method: "get" %>/<%= link_to "edit" ,edit_student_path(students), method: :get %>/<%= link_to "delete" ,student_path(students), method: :delete,
				:confirm => 'Are you sure?' %></td>
			</tr>
			<% end %>
		</table>
	<p><%= link_to "new" , action: "new" %></p>
	<p><%= link_to "DoQueries", action: "doquery" %></p>
</div>

app/views/students/new.html.erb
<div>
	<%= form_for :students, url: {action: "create", controller: "students"},  method: "post" do |f|%>

			<%= f.label :IDno %>
			<%= f.text_field :IDno %><br />

			<%= f.label :college_id %>
			<%= f.text_field :college_id %><br />

      <%= f.label :department %>
			<%= f.text_field :department %><br />

			<%= f.label :maths %>
			<%= f.text_field :maths %><br />

			<%= f.label :physics %>
			<%= f.text_field :physics %><br />

			<%= f.label :chemistry %>
			<%= f.text_field :chemistry %><br />

			<%= f.label :year%>
			<%= f.text_field :year %><br />

			<%= f.submit %>

		<% end %>
</div>


<!DOCTYPE html>
<html>

<head>
  <style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }
  </style>
  <script src="https://code.jquery.com/jquery-3.0.0.min.js" integrity="sha256-JmvOoLtYsmqlsWxa7mDSLMwa6dZ9rrIdtrrVYRnDRH0=" crossorigin="anonymous"></script>
  <script type="text/javascript">
    function loadStudent() {  
      $.ajax({
         url: 'http://localhost:3000/students/' + $(".id").val(),
         data: {},
         type: 'GET',
         error: function() {
            debugger
            alert("Error!");
            $('#info').html('<p>An error has occurred</p>');
         },
         success: function(data) {
          alert("content loaded successfully!");
          var student = data;
            var table = $("<table></table>");

            var tr1 = $("<tr></tr>");
            var td1 = $("<td></td>");
            td1.text("id");
            tr1.append(td1);
            var td2 = $("<td></td>");
            td2.text("college_id");
            
            tr1.append(td2);
            var td3 = $("<td></td>");
            td3.text("department");
            
            tr1.append(td3);
            var td4 = $("<td></td>");
            td4.text("maths");
            
            tr1.append(td4);
            var td5 = $("<td></td>");
            td5.text("physics");
            
            tr1.append(td5);
            var td6 = $("<td></td>");
            td6.text("chemistry");
            
            tr1.append(td6);
            var td7 = $("<td></td>");
            td7.text("year");
            
            tr1.append(td7);

            var tr2 = $("<tr></tr>");
            var td1 = $("<td></td>");
            td1.text(data["id"]);
            tr2.append(td1);
            var td2 = $("<td></td>");
            td2.text(data["college_id"]);
            
            tr2.append(td2);
            var td3 = $("<td></td>");
            td3.text(data["department"]);
            
            tr2.append(td3);
            var td4 = $("<td></td>");
            td4.text(data["maths"]);
            
            tr2.append(td4);
            var td5 = $("<td></td>");
            td5.text(data["physics"]);
            
            tr2.append(td5);
            var td6 = $("<td></td>");
            td6.text(data["chemistry"]);
            
            tr2.append(td6);
            var td7 = $("<td></td>");
            td7.text(data["year"]);
            
            tr2.append(td7);
            table.append(tr1);
            table.append(tr2);

            $(".student-json").html(table);      
         }
      });

    }
  </script>
</head>


<p>
  <input type="text" class="id"/>
  <a href="#" onclick = "loadStudent()">load student</a>
  <div class="student-json">
  </div>
</p>
</html>

app/views/students/queries.html.erb
<p>
<%= @mean_hash %>
</p>

<p>

<%= @sorted %>
</p>

<p>
<%= @sorted %>
</p>

<style>
table {
    border-collapse: collapse;
}

table, tr,td, th {
    border: 1px solid black;
}
</style>



<h1> GROUPBY <%=@grpby_id_dept_year%> </h1>

<div>
	
	<table style = "width:20%">
		<tr>
			<th><%= @grpby_id_dept_year %></th>
			<% @mean_hash[@mean_hash.keys[0]].keys.each do |k| %>
			<th><%= k %> </th> 
			<% end %>
		</tr>
		<% @mean_hash.keys.each do |h| %>
		<tr>
			<td><%= h %></td>
			<% @mean_hash[h].keys.each do |k| %>
			<td><%= @mean_hash[h][k].round(2) %> </td> 
			<% end %>
		</tr>
		<% end %>
	</table>
</div>
<%= @sorted[0].keys%>
<% @sorted.each do |h| %>
<%= h %>
<% end %>

<h1> SORTBY </h1>

<div>
	<table style = "width:20%">
		<tr>
			<% @sorted[0].keys.each do |k| %>
				<th><%= k %> </th> 
			<% end %>
		</tr>
		<% for h in 0..(@sorted.length-1) %>
			<tr>
				<% @sorted[h].keys.each do |k| %>
					<td><%= @sorted[h][k] %> </td> 
				<% end %>
			</tr>
		<% end %>
	</table>
</div>




<p><%= @grp_newarr%></p>
<p><%= @meanhash_to_arr_of_hashes%></p>

<h1> SHOW TOTAL </h1>

<div>
	<table style = "width:20%">
		<tr>
			<% @sumhash_to_arr_of_hashes[0].keys.each do |k| %>
				<th><%= k %> </th> 
			<% end %>
		</tr>
		<% for h in 0..(@sumhash_to_arr_of_hashes.length-1) %>
			<tr>
				<% @sumhash_to_arr_of_hashes[h].keys.each do |k| %>
					<td><%= @sumhash_to_arr_of_hashes[h][k] %> </td> 
				<% end %>
			</tr>
		<% end %>
	</table>
</div>


<p> <%= @output_compared%> </p>

app/views/students/show.html.erb
<!DOCTYPE html>
<html>

<head>
  <style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }
  </style>
  <script src="https://code.jquery.com/jquery-3.0.0.min.js" integrity="sha256-JmvOoLtYsmqlsWxa7mDSLMwa6dZ9rrIdtrrVYRnDRH0=" crossorigin="anonymous"></script>
  <script type="text/javascript">
    function loadStudent() {  
      $.ajax({
         url: 'http://localhost:3000/students/' + $(".id").val(),
         data: {},
         type: 'GET',
         error: function() {
            debugger
            alert("Error!");
            $('#info').html('<p>An error has occurred</p>');
         },
         success: function(data) {
          alert("content loaded successfully!");
          var student = data;
            var table = $("<table></table>");

            var tr1 = $("<tr></tr>");
            var td1 = $("<td></td>");
            td1.text("id");
            tr1.append(td1);
            var td2 = $("<td></td>");
            td2.text("college_id");
            
            tr1.append(td2);
            var td3 = $("<td></td>");
            td3.text("department");
            
            tr1.append(td3);
            var td4 = $("<td></td>");
            td4.text("maths");
            
            tr1.append(td4);
            var td5 = $("<td></td>");
            td5.text("physics");
            
            tr1.append(td5);
            var td6 = $("<td></td>");
            td6.text("chemistry");
            
            tr1.append(td6);
            var td7 = $("<td></td>");
            td7.text("year");
            
            tr1.append(td7);

            var tr2 = $("<tr></tr>");
            var td1 = $("<td></td>");
            td1.text(data["id"]);
            tr2.append(td1);
            var td2 = $("<td></td>");
            td2.text(data["college_id"]);
            
            tr2.append(td2);
            var td3 = $("<td></td>");
            td3.text(data["department"]);
            
            tr2.append(td3);
            var td4 = $("<td></td>");
            td4.text(data["maths"]);
            
            tr2.append(td4);
            var td5 = $("<td></td>");
            td5.text(data["physics"]);
            
            tr2.append(td5);
            var td6 = $("<td></td>");
            td6.text(data["chemistry"]);
            
            tr2.append(td6);
            var td7 = $("<td></td>");
            td7.text(data["year"]);
            
            tr2.append(td7);
            table.append(tr1);
            table.append(tr2);

            $(".student-json").html(table);      
         }
      });

    }
  </script>
</head>



<body>
<div>  
  <table style="width:100%" border = "0">
    <tr>
    	<td>id</td>
      <td>college_id</td>
      <td>extendedId</td>
      <td>IDno</td>
      <td>department</td>
      <td>maths</td>
      <td>physics</td>
      <td>chemistry</td>
      <td>year</td>
    </tr>
    
    <tr>
      <td><%= @student.id %> </td> 
      <td><%= @student.college_id %> </td> 
      <td><%= @student.extendedId %> </td>
      <td><%= @student.IDno %> </td> 
      <td><%= @student.department %></td>
      <td><%= @student.maths %></td>
      <td><%= @student.physics %></td>
      <td><%= @student.chemistry %></td>
      <td><%= @student.year %></td>
    </tr>
  </table>
</div>

<p>
  <input type="text" class="id"/>
  <a href="#" onclick = "loadStudent()">load student</a>
  <div class="student-json">
  </div>
</p>
</body>
</html>