config/routes.rb
Vishnuapp::Application.routes.draw do

=begin
  get "colleges/:index"

  get "colleges/:show"

  get "colleges/:new"

  get "colleges/:edit"

  get "colleges/:update"

  get "colleges/:create"
=end
  resources :students do  # ,    only: [ :index ] 
    member do    
    end

    collection do
      get "doquery"  
      get "queries"
    end
  end  

  resources :colleges do
      member do 
      end

      collection do
      
        get "results"
        get "listing"
      end
  end  

end

app/models/college.rb
class College < ActiveRecord::Base
	attr_accessible :college_name, :esta_year
	has_many :student
	before_update :clg_namechange
	students_changedcollege = Array.new

  	def clg_namechange
  		Rails.logger.debug "Updatinppp2222222222gggggggggggggg Record #{self.college_name.inspect}"
  		students_list = College.find(self.id.to_i).student
  		#Rails.logger.debug "Updatinppp2222222222gggggggggggggg Record #{students_changedcollege.inspect}"
  		for i in 0..(students_list.length-1)

	 		students_list[i][:extendedId] = students_list[i][:id].to_s << "_" << self.college_name[0,2].to_s << "_" << self.id.to_s
	 		#College.find(self.id.to_i).student[i].save
	 		#Rails.logger.debug "Updatinppp2222222222gggggggggggggg Record #{College.find(self.id.to_i).student[i].extendedId.inspect}"

	 		Rails.logger.debug "Updatinppp2222222222gggggggggggggg Record #{students_list[i].inspect}"
	 	end
	end
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
	def index
	  	@colleges = College.all
	  	Rails.logger.debug "In sssssssssssssssssss: #{params.inspect}"
	  	#@collegesh = College.find(params[:id])
	end

	def show
	 	@college = College.find(params[:id])
	end

	def new
	  	@colleges = College.new
	end

	def edit
	  	@colleges = College.find(params[:id])
	end

	def listing
		gaga = College.find(params[:format])
		Rails.logger.debug "Updatinpppppppppppppppppppgggggggggggggg Record #{gaga.inspect}"

		@pass = gaga.student
		Rails.logger.debug "Updatinggggggggggggggggggggggggg Record #{@pass.inspect}"
	end

	def update
	  	@colleges =College.find(params[:id])
	  	@colleges.update_attributes(params[:colleges])
	  	redirect_to action: :index
	end

	def create
	  	@colleges = College.create(params[:colleges])
	  	redirect_to action: :index
	end

	def destroy
	  	@colleges = College.find(params[:id])
	  	@colleges.destroy
	  	redirect_to action: :index
	end

	def search
	  	
	end

	def results
	  	data = College.all
	  	Rails.logger.debug "Updatinggggggggggggggggggggggggg Record #{params.inspect}"
	  	Rails.logger.debug "Updatinggggggggggggggggggggggggg Record #{data.inspect}"
	  	input = params[:temp][:vars].to_s
	  	
	  	@my_string = Array.new
	  	for i in 0..(data.length-1)
	  		
			if data[i][:college_name].include? input
			@my_string.push(data[i])
			end
			Rails.logger.debug "Updatinggggggggggggggggggggggggg Record #{@my_string.inspect}"

		end
	end
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/views/colleges/edit.html.erb
<div>
  <%= form_for :colleges,url: { action: "update",controller: "colleges"}, method:"put" do |f|%>

        <%= f.label :college_name %>
        <%= f.text_field :college_name %><br />

        <%= f.label :esta_year %>
        <%= f.text_field :esta_year %><br />

        <%= f.submit %>

    <% end %>
</div>

app/views/colleges/index.html.erb
<div>
	<body BGCOLOR="#FFFFFF" TEXT="#000000"  >
		
		<table style="width:100%" border = "0">
		  <tr>
		  	<td>id</td>
		    <td>college_name</td>
		    <td>esta_year</td>
		    <td>actions</td>
		  </tr>
		 <% @colleges.each do |colleges| %>
			<tr>
				<td><%= colleges.id %> </td> 
				<td><%= colleges.college_name %> </td> 
				<td><%= colleges.esta_year %></td>
			    <td><%= link_to "show" ,college_path(colleges),method: "get" %>/<%= link_to "edit" ,edit_college_path(colleges), method: :get %>/<%= link_to "delete",college_path(colleges), method: :delete,
				    :confirm => 'Are you sure?' %>/<%= link_to "students" ,listing_colleges_path(colleges), method: :get %></td>
			</tr>
			<% end %>
		</table>
		<p><%= link_to "new" , action: "new" %></p>
		<p><%= link_to "DoQueries" %></p>
		<p>
			<%= form_for :temp,url: {action: "results"}, method: :get  do |f|%>
				search: <%= f.text_field :vars %>

				<%= f.submit :search %>
			<% end %>
		</p>
	</body>
</div>

app/views/colleges/listing.html.erb
<p>you didn't completed it</p>



<div>
	<%= @pass %>
</div>

app/views/colleges/new.html.erb
<div>
	<%= form_for :colleges, url: {action: "create", controller: "colleges"},  method: "post" do |f|%>

			<%= f.label :college_name %>
			<%= f.text_field :college_name %><br />

			<%= f.label :esta_year %>
			<%= f.text_field :esta_year %><br />

			<%= f.submit %>

		<% end %>
</div>

app/views/colleges/results.html.erb
<%= @my_string%>

<p>
<%= @array%>
</p>

app/views/colleges/show.html.erb
<div>  
  <table style="width:100%" border = "0">
    <tr>
      <td>id</td>
      <td>college_name</td>
      <td>esta_year</td>
    </tr>
    
    <tr>
      <td><%= @college.id %> </td> 
      <td><%= @college.college_name %> </td> 
      <td><%= @college.esta_year %></td>
    </tr>
  </table>
</div>